repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-added-large-files
      exclude_types: [yaml]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      exclude: docs/source/conf.py
      args: [--max-line-length=110]

- repo: https://github.com/psf/black
  rev: 21.5b2
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.yaml
          )$
      args:
        - --quiet-level=2

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.1
  hooks:
    - id: pyupgrade
      args:
        - --py36-plus

- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      additional_dependencies: [toml]
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.10.0
  hooks:
    - id: nbqa-black
      args: [--nbqa-mutate]
    - id: nbqa-pyupgrade
      args: [--nbqa-mutate, --py36-plus]
